### ISSUE TITLE
1.19 Support

### ISSUE THREAD

**Issue by Loren314** [btwonion/SimpleAutoDrop#2]
The mod requires a 1.19.2 version of silk-all and fabric api, so the mod doesn't work for 1.19 and likely not for 1.19.1 either. Otherwise, a pretty good mod.

**Comment by btwonion** [comment]
oh yeah good point. i will fix this in the next days. thanks for repoting this. i only play the latest versions :)

**Comment by btwonion** [comment]
@Loren314 just a quick question. Why do you play 1.19 instead of 1.19.2?

**Comment by btwonion** [comment]
i will not change it. anyways it's better to always use the latest subversion of a major versions.

**Comment by btwonion** [comment]
just use a mod manager like https://github.com/jakobkmar/pacmc
